# Generated by Django 2.2.1 on 2019-12-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_rating', '0002_auto_20191210_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
